spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpth: schema-all.sql
#    initialization-mode: ALWAYS
